1 more zoom lvl + padding around markers
GauChoob/bs-cartography pull request #2
Opened 2024-12-14 18:37 UTC by samszotkowski

Allow zooming in 1 extra level, and add a bit of space around the entity icons. Example how it looks after:
![image](https://github.com/user-attachments/assets/20488e33-5acd-4cef-b79f-8d5ad84e2962)

See also: https://brightershoreswiki.org/w/User:Microbrews/Common.less/leaflet.less for a couple more changes -- adding shadow to the entity icons + making corners more rounded + at the very bottom I added `image-rendering:pixelated` hoping that will make the browser use nearest-neighbor when zooming into the max level. Not sure whether that was the right class to put it on though, but it worked when I put it on my user css anyway.

2024-12-14 18:39 UTC, samszotkowski commented
Oh I also had the default zoom increase by 1 level, I felt this was just a hair too far zoomed out for the default case
![image](https://github.com/user-attachments/assets/ffed5edc-0aaf-4dbc-b8b7-f9d4ead44cd5)

2024-12-14 20:30 UTC, GauChoob commented
Great suggestions! I don't know if you can make the small changes I recommended above?

Cheers!

Gau

2024-12-14 20:37 UTC, GauChoob requested changes

2024-12-14 20:37 UTC, GauChoob commented on src/index.js
> +    maxNativeZoom: config.maxZoom-1,
config.maxZoom - 1 is not really maintainable. It's better to keep all of this in the config file. Could you create config.minNativeZoom and config.maxNativeZoom in config.js in the source image properties section (lines 1-16) and config.minZoom and config.maxZoom in the map properties section (lines 18-28)?

2024-12-14 20:37 UTC, GauChoob commented on src/markers.js
> +        const padding = tile_width / 6  // want there to be small gap between icon and tile boundary
Can you add the padding as an option in config.js instead of directly defining it in this function?

2024-12-14 20:37 UTC, GauChoob commented on src/markers.js
> +        icon.options.iconSize = [Math.max(config.entity_minimum_width, tile_width*this.entity_size[0]-padding), Math.max(config.entity_minimum_width, tile_width*this.entity_size[1]-padding)]
Personally I prefer spaces before/after my minus signs. Maybe it's just me? XD

2024-12-15 00:49 UTC, GauChoob approved these changes

2024-12-15 00:49 UTC, merged